### ISSUE TITLE
Feature request: additional command line options

### ISSUE THREAD

**Issue by cheshire** [dbeyer/benchexec#28]
Hi,
I often find myself editing the XML file repeatedly to turn on/off some options, which gets error prone.
What if we allow to set properties on the command line? E.g. we can say that all options after `--` gets passed to the binary, as in e.g. `$ benchexec blah.xml -- -setprop optionIWant=True`.

In a similar vein, I think it would be very useful to have an option which would allow to set a name for the output `.xml` file, as again often it is tiresome to create a new config file just to set one option to `true`.
Something like `$ benchexec blah.xml --out=myresults.xml`

Thoughts?

**Comment by PhilippWendler** [comment]
With respect to adding command-line flags on the command line, I think that could be done. I would prefer to enforce the usage of `--` though and I don't know whether our argument-parsing library supports this or we have to find a workaround.

I wonder however why you find it more error-prone to edit the XML than the command itself? After all, the latter is quite transient whereas the XML file is edited with a proper editor, stored persistently, can be copied to have multiple (named) versions, can be versioned etc. The idea of this XML-based input file was actually to allow all important parameters to be defined in a persistent file such that this can be stored and the benchmark can be reproduced easily later. For example, when doing benchmarks for a paper I would strongly recommend to have everything in the XML file and check this file into the paper repository. Otherwise it will be difficult and error-prone to exactly reproduce these benchmarks half a year later for the next paper version.

For your second suggestion, the parameter `-n`/`--name` is intended for this.

**Comment by cheshire** [comment]
Right, I see, I think this is save to close.
My main point of confusion was that I did not realize I can create multiple run definitions, and then switch between them on the command line with `-r` flag.
Before I was duplicating whole files, or temporarily tweaking one file (eg to change one option out of N)
