### ISSUE TITLE
How to add dynamic library?

### ISSUE THREAD

**Issue by cgcgbcbc** [dbeyer/benchexec#85]
If my archive has dynamic library that some of my binaries depend on, should I copy the dynamic library into /usr/local/lib in the very beginning of my executable?

**Comment by kfriedberger** [comment]
You will not have write-access to any directory except $TMD_DIR, $HOME_DIR and the current working directory. If your tool depends on a dynamic library, then it should be located in the current working directory (or some sub-directory of it, for example "./lib/"). When executing your tool, you can set the environment variable "LD_LIBRARY_PATH" to include the corresponding directory.

Examples:
direct cmdline:
```
LD_LIBRARY_PATH=./lib:$LD_LIBRARY_PATH myExecutableTool
```
within some bash-script:
```
export LD_LIBRARY_PATH=./lib:$LD_LIBRARY_PATH
myExecutableTool
```
There are also other ways to tell your tool where to find the libraries, 
but LD_LIBRARY_PATH is the easiest way to do it.

**Comment by PhilippWendler** [comment]
Be careful: the writable paths are actually named `$TMPDIR` and `$HOME`.

Note that I would recommend a different solution than setting `$LD_LIBRARY_PATH`, because relying on the current working directory by including `./lib` or similar makes it quite fragile and forces the user without need to execute the tool exactly in the right directory.

Much better is it to tell the linker at compilation time where to look for libraries using the `-rpath` flag. By using the string `$ORIGIN` you can tell the linker to look for libraries in a directory *relative to the location of the current executable*. This is typically exactly what one wants, and it works no matter what the current directory is.

I have written about this [here](http://stackoverflow.com/a/16234339/396730) (just ignore the first half of the post), and it is described in the [man page of ld.so](http://linux.die.net/man/8/ld.so).

**Comment by cgcgbcbc** [comment]
Thank you all a lot !

**Comment by cgcgbcbc** [comment]
@PhilippWendler 
Now everything works fine except for libstdc++.so, it seems that it is still use the library in the default location of runtime machine.

readelf -d gives the following output:
```
0x0000000000000001 (NEEDED)             Shared library: [librt.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [ld-linux-x86-64.so.2]
 0x000000000000000f (RPATH)              Library rpath: [$ORIGIN]
```
And error messages are:
```
./sv_absref: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by ./sv_absref)
./sv_absref: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./sv_absref)
./sv_absref: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./sv_absref)
```
It still use libstdc++.so on default location and does not use which I provided.

**Comment by cgcgbcbc** [comment]
Now I link everything statically except librt and avoid this problem...
