### ISSUE TITLE
-N parameter lead to crash

### ISSUE THREAD

**Issue by cgcgbcbc** [dbeyer/benchexec#90]
I found that if I use -N parameter for parallel run, results are much much more different compared to that without -N parameter, and most are crash.

**Comment by kfriedberger** [comment]
Can you give more detail, please.
What component does crash?
Which tool do you execute? Which limitations? Which benchmark? 
Does your tool itself depend on being executed as a single instance?
Does your tool produce any output with a hard-coded filename (and thus multiple instances write to the same file?

**Comment by cgcgbcbc** [comment]
My tool's name is ceagle_absref，I only set time limit with -T 90 for testing on bitvector, float and recursive set. My tool produce output with input name as prefix. What do you mean by being exectuted as single instance？

**Comment by kfriedberger** [comment]
There are some tools, that can only be executed as "single instance", because one of the following points is valid:
- The tool (or some of its sub-processes) writes into temporary files with equal names. Either overridden or deleted content might cause a crash. This is the reason for most tools.
- The tool requires a special port (network), which can be used to communicate. A second instance of the tool might crash, because the port is blocked by the first instance.
- The tool contains some evil kill-method like "killall xyz", where "xyz" is a sub-process of the tool. A second instance also kills the first instance.

Can you provide a stack-trace or a error-message?

**Comment by cgcgbcbc** [comment]
I figure out the problem is that one component of my tool writing by my coauthor write a hard coding temp file...
